export { MenuContentPage } from "./menu-content.page";
export { LoginPage } from "./login.page";
export { AddressStepPage } from "./address-step.page";
export { ProductListPage } from "./products-list.page";
export { ShopingCartPage} from "./shoping-cart.page";
export { ShippingStepPage} from "./shipping-step.page";
export { PaymentStepPage} from "./payment-step.page";
export { DressesListPage} from "./dresses-list.page";
export { PersonalFormPage } from "./forms.page";
export { UploadPage } from "./upload.page";
export { DownloadPage } from "./download.page";
export { IframePage } from "./iframe.page";
